# Disable the blank line at the start of the prompt
# add_newline = true

format = """
$character\
$directory\
$git_branch\
$git_status\
"""

[git_branch]
disabled = true

[git_status]
disabled = true

[directory]
format = "[ $path]($style)[ > ]( bold white )"
# format = "[ $path]($style)[: ]( white )"
style = "#41a6b5"
# truncation_length = 1
# truncation_symbol = ""
truncate_to_repo = false

[character]
success_symbol = " [](bold white)"
error_symbol = " [](bold red)"
# success_symbol = " [](bold white)"
# error_symbol = " [](bold red)"
