add_newline = true

format = """
$character\
$directory\
$git_branch\
$git_status\
"""

[git_branch]
disabled = true

[git_status]
disabled = true

[directory]
format = "[ $path]($style)[ > ](bold white)"
style = "#41a6b5"
truncate_to_repo = false

[character]
success_symbol = " [](bold white)"
error_symbol = " [](bold red)"
vimcmd_symbol = " [](bold green)"
vimcmd_replace_one_symbol = " [](bold purple)" 
vimcmd_replace_symbol = " [](bold purple)" 
vimcmd_visual_symbol = " [](bold yellow)" 
