schemaVersion = 1

[catalogConfiguration]
customFolders = []

    [[catalogConfiguration.folderDepthOverrides]]
    catalogIdentifier = 'TunaCore.UserFoldersCatalog'
    depthRawValue = 5

    [[catalogConfiguration.scriptsDirectories]]
    id = 'EF946476-413C-4FAE-A73F-3C1A9FF7E88D'
    path = '~/git_repos/dotfiles/.config/tuna/bin'

[hotkeys]
custom = []

    [hotkeys.app.activate]
    carbonKeyCode = 36
    carbonModifiers = 256

    [hotkeys.app.leaderMode]
    carbonKeyCode = 49
    carbonModifiers = 256

[[leaderMode.bindings]]
key = 'f'
url = 'tuna://run/path.%252FSystem%252FLibrary%252FCoreServices%252FFinder.app/Open'

[[leaderMode.bindings]]
key = 'm'
url = 'tuna://run/path.%252FSystem%252FApplications%252FMessages.app/Open'

[[leaderMode.bindings]]
key = 'n'
url = 'tuna://run/path.%252FSystem%252FApplications%252FNotes.app/Open'

[[leaderMode.bindings]]
key = 'p'
url = 'tuna://run/TunaCore.AllApplicationsCatalog.1Password/Open'

[[leaderMode.bindings]]
iconPath = '/Library'
key = 'd'
url = 'tuna://run/TunaCore.AllApplicationsCatalog.Discord/Open'

[[leaderMode.bindings]]
key = 'b'
url = 'tuna://run/TunaCore.AllApplicationsCatalog.Vivaldi/Open'

[[leaderMode.bindings]]
key = 's'
url = 'tuna://run/TunaCore.AllApplicationsCatalog.Spotify/Open'

[[leaderMode.bindings]]
key = 't'
url = 'tuna://run/TunaCore.AllApplicationsCatalog.Slack/Open'

[[leaderMode.bindings]]
iconPath = '/Applications/Tuna.app'
key = 'space'
url = 'tuna://run/Tuna.ModesCatalog.Fuzzy%20Mode/TunaCore.CommonActionsCatalog.Switch'

[[leaderMode.bindings]]
key = 'c'
url = 'tuna://run/Tuna.Internal.ClipboardProxyCatalog.Clipboard%20History/Tuna.BasicActionsCatalog.Browse'

[[leaderMode.bindings]]
key = 'g'
url = 'tuna://run/TunaCore.AllApplicationsCatalog.Ghostty/Open'

[[leaderMode.bindings]]
key = 'z'
url = 'tuna://run/TunaCore.AllApplicationsCatalog.Google%20Meet/Open'

[[leaderMode.bindings]]
iconPath = '/System/Applications/Mission Control.app'
key = 'w'
label = 'window management'

    [[leaderMode.bindings.children]]
    key = 'm'
    url = 'tuna://run/TunaSystem.WindowManagementCatalog.Almost%20Maximize/TunaCore.CommonActionsCatalog.Run%20in%20Background'

[[leaderMode.bindings]]
key = 'u'
label = 'utility'

    [[leaderMode.bindings.children]]
    key = 's'
    url = 'tuna://run/TunaCore.SystemApplicationsCatalog.Screenshot/Open'

[settings]
backspaceBehavior = 'deleteCharacters'
leaderModeModifierTrigger = 'rightOption'
resultListNavigationBindings = 'vimStyle'
showResultsImmediatelyOnActivation = true
switchToTextModeWhenNoResults = true
themeIdentifier = 'com.brnbw.tuna.themes.default'