default_startup_script = "~/git_repos/dotfiles/sesh/bin/default.sh"

[[startup_scripts]]
session_path = "~/git_repos/sesh"
script_path = "~/git_repos/dotfiles/sesh/bin/sesh.sh"

[[startup_scripts]]
session_path = "~/git_repos/dotfiles/spotify-player"
script_path = "~/git_repos/dotfiles/sesh/bin/spotify.sh"
