return {
  "stevearc/conform.nvim",
  event = { "BufReadPre", "BufNewFile" },
  opts = {
    formatters_by_ft = {
      javascript = { "prettierd" },
      typescript = { "prettierd" },
      javascriptreact = { "prettierd" },
      typescriptreact = { "prettierd" },
      css = { "prettierd", "stylelint" },
      html = { "prettierd" },
      json = { "prettierd" },
      yaml = { "prettierd" },
      markdown = { "prettierd" },
      graphql = { "prettierd" },
      lua = { "stylua" },
      -- python = { "autoflake", "autopep8", "isort", "black" },
      python = { "ruff" },
      go = { "gofumpt", "goimports", "golines" },
      fish = { "fish_indent" },
      bash = { "shfmt" },
      -- gotmpl = { "prettier" },
    },
  },
}
